-- 第二階段回復（後台或報名若有異常，貼這段立即還原）
ALTER TABLE customers       DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_tours  DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles        DISABLE ROW LEVEL SECURITY;
ALTER TABLE crm_labels      DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE tour_blog_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE tour_itinerary  DISABLE ROW LEVEL SECURITY;
